spring:
    application:
        name: identity-service
    datasource:
        url: jdbc:postgresql://localhost:5432/ticsys_identity_service_db
        username: postgres
        password: pqkiet854A@
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate.ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

server:
    port: 8085

logging:
    level:
        root: INFO
        '[org.springframework.security]': DEBUG
        
jwt:
    signer-key: 1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij
    expiration: 3600
    refresh-token-expiration: 86400

otp:
    length: 6
    expiry_minutes: 5
    
# Disable Eureka cho test
eureka:
    client:
        enabled: false  # Tắt Eureka client
        register-with-eureka: false
        fetch-registry: false

grpc:
    server:
        port: 9095
    client:
        notification-service:
            negotiationType: plaintext
            enableKeepAlive: true
            discovery:
                enabled: true
                selector: metadata
                metadataKey: grpc.port