spring:
    application:
        name: identity-service
    datasource:
        url: jdbc:postgresql://localhost:5432/ticsys_identity_service_db
        username: postgres
        password: pqkiet854A@
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate.ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
server:
    port: 8085

logging:
    level:
        root: INFO
        '[org.springframework.security]': DEBUG
        
jwt:
    signer-key: 1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij
    expiration: 3600

    refresh-token-expiration: 86400
otp:
    length: 6
    expiry_minutes: 5
    
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
        register-with-eureka: true
        fetch-registry: true
    instance:
        prefer-ip-address: true
        hostname: localhost
        ip-address: 127.0.0.1
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        metadata-map:
            grpc.port: "${grpc.server.port}" 

grpc:
    server:
        port: 9095
    client:
        notification-service:
            negotiationType: plaintext
            enableKeepAlive: true
            discovery:
                enabled: true
                selector: metadata
                metadataKey: grpc.port

