spring:
    application:
        name: order-service
    datasource:
        url: jdbc:postgresql://localhost:5432/ticsys_order_service_db
        username: postgres
        password: pqkiet854A@
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate.ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
server:
    port: 8086

logging:
    level:
        root: INFO
        '[org.springframework.security]': DEBUG
    
    
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
        register-with-eureka: true
        fetch-registry: true
    instance:
        prefer-ip-address: true
        hostname: localhost
        ip-address: 127.0.0.1
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        metadata-map:
            grpc.port: "${grpc.server.port}" 

grpc:
    client:
        notification-service:
            negotiationType: plaintext
            enableKeepAlive: true
            discovery:
                enabled: true
                selector: metadata
                metadataKey: grpc.port
        event-service:
            negotiationType: plaintext
            enableKeepAlive: true
            discovery:
                enabled: true
                selector: metadata
                metadataKey: grpc.port
        user-service:
            negotiationType: plaintext
            enableKeepAlive: true
            discovery:
                enabled: true
                selector: metadata
                metadataKey: grpc.port
