spring:
    application:
        name: event-service
    datasource:
        url: jdbc:postgresql://localhost:5432/ticsys_event_service_db
        username: postgres
        password: pqkiet854A@
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate.ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

server:
    port: 8082

# Disable Eureka cho test
eureka:
    client:
        enabled: false  # Tắt Eureka client
        register-with-eureka: false
        fetch-registry: false

grpc:
    server:
        port: 9096